name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Build Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
